# 用于浏览器标签的图标
# Icon for browser tab
favicon: /favicon_io/favicon.ico

# 用于苹果设备的图标
# Icon for Apple touch
apple_touch_icon: /favicon_io/apple-touch-icon.png


# 导航栏的相关配置
# Navigation bar
navbar:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
  blog_title: "细风の后花园"

  # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
  # Navigation bar menu. `key` is used to associate languages/*.yml. If there is no association, the value of `key` itself will be displayed; if `icon` is a css class, it can be omitted; adding `name` can force the display of the specified name
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "note", 
        link: "/note/", 
        submenu: [
          {key: 'leetcode', link: '/categories/note/leetcode/'},
        ],
        icon: "iconfont book icon-book" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }


#---------------------------
# 首页
# Home Page
#---------------------------
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  # Path of Banner image, can be a relative path or an absolute path, the same on other pages
  banner_img: /img/index.png

  # 首页副标题的独立设置
  # Independent config of home page subtitle
  slogan:
    enable: true

    # 为空则按 hexo config.subtitle 显示
    # If empty, text based on `subtitle` in hexo config
    text: "一直不停的想······"


#---------------------------
# 关于页
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/default.png
  avatar: /img/portrait.jpg
  name: "Xifeng"
  intro: "An back garden for Xifeng"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/XifengGood", tip: "GitHub" }
    - { class: "iconfont icon-douban-fill", link: "https://www.douban.com/people/175810874", tip: "豆瓣" }
    - { class: "iconfont icon-bilibili-fill", link: "https://space.bilibili.com/359493562", tip: "哔哩哔哩" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/wechat_qrcode.jpg", tip: "WeChat" }
    - { class: "iconfont icon-qq-fill", qrcode: "/img/qq_qrcode.png", tip: "QQ" }

#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  math:
    enable: true
    specific: false
    engine: mathjax

  comments:
    enable: true
    type: gitalk

  # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）
  # Update date is displayed at the beginning of the post. The default date is the update date of the md file, which can be manually specified by `updated` in front-matter (same format as date)
  updated:
    enable: true

    # 格式参照 ISO-8601 日期格式化
    # ISO-8601 date format
    # See: http://momentjs.cn/docs/#/parsing/string-format/
    date_format: "LL a"

    # 是否使用相对时间表示，比如："3 天前"
    # If true, it will be a relative time, such as: "3 days ago"
    relative: true

    # 提示标签类型
    # Note class
    # Options: default | primary | info | success | warning | danger | light
    note_class: info

#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  comments:
    enable: true
    type: gitalk
  
  # 友链的成员项
  # Member item of page
  items:
    - {
      title: "Fluid Blog",
      intro: "主题博客",
      link: "https://hexo.fluid-dev.com/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Docs",
      intro: "主题使用指南",
      link: "https://hexo.fluid-dev.com/docs/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Repo",
      intro: "主题 GitHub 仓库",
      link: "https://github.com/fluid-dev/hexo-theme-fluid",
      avatar: "/img/favicon.png"
    }

  custom:
    enable: true
    content: '<hr><p>在下方留言申请加入我的友链，按如下格式提供信息：</p><ul><li>博客名：Fluid</li><li>简介：Fluid 主题官方博客</li><li>链接：https://hexo.fluid-dev.com</li><li>图片：https://hexo.fluid-dev.com/img/favicon.png</li></ul>'

gitalk:
  owner: XifengGood
  admin: ['XifengGood']
  repo: gitalk-comments
  clientID: Ov23liqtvAkyLhpFDrHE
  clientSecret: 70dc00cda979ef006734e668cf095d1cd0a84ba9
  language: zh-CN
  labels: ['Gitalk']
  perPage: 10  # 每页评论数
  id: location.pathname
  pagerDirection: last
  distractionFreeMode: false
  createIssueManually: true
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token